# Generated by Django 4.2 on 2023-04-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='budget',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
